openapi: 3.0.0
info:
  version: 0.2.0
  title: Pregxas API
  description: |
    The API for the Pregxas platform

    *Notice a bug? Something wrong? Want to provide feedback? Send us an email at support@treelightsoftware.com!*

    *WARNING: Usage of non-documented APIs is not supported and may change without warning or notification!*

  contact: 
    name: Treelight Software
    email: support@treelightsoftware.com
    url: https://www.treelightsoftware.com

servers:
  - url: https://api.pregxas.com

security:
  - ApiKeyAuth: []

tags:
  $ref: "tags.yaml#/Tags"

paths:
  ## SITE ##
  /admin/site:
    $ref: "sitePaths.yaml#/SiteInfoPath"
  ## USERS ##
  /me:
    $ref: "userPaths.yaml#/UserProfilePath"
  /users/login:
    $ref: "userPaths.yaml#/UserLoginPath"
  /users/reset:
    $ref: "userPaths.yaml#/PasswordResetPath"
  /users/reset/verify:
    $ref: "userPaths.yaml#/PasswordResetVerifyPath"
  ## PRAYER REQUESTS ##
  /requests:
    $ref: "requestPaths.yaml#/PrayerRequestsPath"
  /requests/{requestId}:
    $ref: "requestPaths.yaml#/PrayerRequestPath"

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: jwt

  parameters:
    userId:
      name: userId
      in: path
      required: true
      description: The user's database id
      schema:
        type: integer
    requestId:
      name: requestId
      in: path
      required: true
      description: The prayer request's database id
      schema:
        type: integer
    ## Filtering ##
    start:
      name: start
      in: query
      description: The UTC timestamp (YY-MM-DDTHH:mm:SSZ) of when to start the filtering
      schema:
        type: string
        format: datetime
    end:
      name: end
      in: query
      description: The UTC timestamp (YY-MM-DDTHH:mm:SSZ) of when to end the filtering
      schema:
        type: string
        format: datetime
    count:
      name: count
      in: query
      description: The maximum number of elements to return
      schema:
        type: integer
    offset:
      name: offset
      in: query
      description: The offset to begin the filtering by
      schema:
        type: integer
    groupBy:
      name: groupBy
      in: query
      description: What to group the elements by
      schema:
        type: string
  
  responses:
    400Response:
      description: Invalid request, typically due to missing or malformed parameters or body
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: The nature of the error
    401Response:
      description: Not authorized, perhaps due to a missing JWT or API key
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: The nature of the error
              code:
                type: string
                description: A system generated code for the error type
              data:
                type: object
                description: Optional object with additional data
    403Response:
      description: Not allowed
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: The nature of the error
              code:
                type: string
                description: A system generated code for the error type
              data:
                type: object
                description: Optional object with additional data
    404Response:
      description: Not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: The nature of the error
              code:
                type: string
                description: A system generated code for the error type
              data:
                type: object
                description: Optional object with additional data
    409Response:
      description: Conflict or already exists
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: The nature of the error
              code:
                type: string
                description: A system generated code for the error type
              data:
                type: object
                description: Optional object with additional data
    419Response:
      description: User session / JWT expired
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: The nature of the error
              code:
                type: string
                description: A system generated code for the error type
              data:
                type: object
                description: Optional object with additional data
